project:
  type: website
  output-dir: docs

website:
  title: "DataSci JEDI"
  navbar:
    logo: images/jedi-logo.jpg
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - webinars.qmd
      - resources.qmd
      - contact.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    mainfont: Atkinson Hyperlegible
    css: styles.scss
    toc: true

editor: visual

