project:
  type: website
  output-dir: docs

website:
  title: "DataSci JEDI"
  description: "The Justice, Equity, Diversity, and Inclusion (JEDI) Outreach Group, a community of statisticians and data scientists, is committed to communication, programming, and professional development to advance and support a society that values all people."
  favicon: "mages/jedi-logo.jpg"
  site-url: "https://datascijedi.github.io/website/"

  open-graph: true
  twitter-card:
    creator: "@datascijedi"
    image: "images/jedi-logo-square.png"

  page-footer:
    left: "Copyright 2022 © JEDI"
    right:
    - text: "License"
      href: LICENSE.md
    - text: "Code of Conduct"
      href: CODE_OF_CONDUCT.md

  page-navigation: true

  navbar:
    logo: images/jedi-logo.jpg
    align: center
    title: false

    left:
      - text: "Home"
        file: index.qmd
      - text: "About"
        file: about.qmd
      - text: "Activities"
        file: activities.qmd
      - resources.qmd
      - text: "Get involved"
        file: get-involved.qmd

    right:
      - icon: twitter
        file: https://twitter.com/datascijedi
      - icon: linkedin
        file: https://www.linkedin.com/showcase/justice-equity-diversity-and-inclusion-organizing-group
      - icon: instagram
        file: https://www.instagram.com/datascijedi/
      - icon: facebook
        file: https://www.facebook.com/DataSciJEDI/

  sidebar:
    - id: about
      title: "About"
      style: "docked"
      collapse-level: 2
      align: left
      contents:
        - text: "About"
          file: about.qmd
        - file: welcome.qmd
        - file: history.qmd
        - file: mission.qmd

    - id: activities
      title: "Activities"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - text: "Activities"
          file: activities.qmd
        - file: webinars.qmd
        - file: jedi-corner.qmd

format:
  html:
    theme:
      light: [flatly, style.scss]
      dark: [darkly, style.scss]
    mainfont: Atkinson Hyperlegible
    toc: true

editor: visual

execute:
  freeze: auto
