project:
  type: website
  output-dir: _site

  render:
    - "*.qmd"
    - "*.md"
    - "*.ipynb"
    - "*.Rmd"
    - "!CONTRIBUTING.md"
    - "!README-gh-pages.md"

  post-render:
    - copy_gh_pages_readme.js
    - dynamic_github_edit.js

website:
  title: "JEDI Outreach Group"
  description: "The Justice, Equity, Diversity, and Inclusion (JEDI) Outreach Group, a community of statisticians and data scientists, is committed to communication, programming, and professional development to advance and support a society that values all people."
  favicon: "images/jedi-favicon-32px.ico"
  site-url: "https://datascijedi.github.io/website/"

  open-graph: true
  twitter-card:
    creator: "@datascijedi"
    image: "images/jedi-logo-square.png"

  page-footer:
    left: "Copyright 2022 © JEDI"
    center:
    - text: "GH-6c622c2fa6a54817" # placeholder text, replaced in post-render script
    right:
    - text: "License"
      href: LICENSE.md
    - text: "Code of Conduct"
      href: CODE_OF_CONDUCT.md

  page-navigation: true

  navbar:
    logo: images/jedi-logo-square.png
    align: center

    left:
      - text: "About"
        file: about.qmd
      - text: "Activities"
        file: activities.qmd
      - jedi-corner.qmd
      - resources.qmd
      - text: "Get involved"
        file: get-involved.qmd

    right:
      - icon: twitter
        href: https://twitter.com/datascijedi
        aria-label: Twitter
      - icon: linkedin
        href: https://www.linkedin.com/showcase/justice-equity-diversity-and-inclusion-organizing-group
        aria-label: LinkedIn
      - icon: instagram
        href: https://www.instagram.com/datascijedi/
        aria-label: Instagram
      - icon: facebook
        href: https://www.facebook.com/DataSciJEDI/
        aria-label: Facebook
      - icon: github
        href: https://github.com/datascijedi/website
        aria-label: GitHub

  sidebar:
    - id: about
      title: "About"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - text: "About"
          file: about.qmd
        # - file: welcome.qmd
        # - file: history.qmd

    - id: activities
      title: "Activities"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - text: "Activities"
          file: activities.qmd
        - file: webinars.qmd
        - file: weekly-newsletter.qmd

format:
  html:
    theme:
      light: [flatly, style.scss]
      dark: [darkly, darkstyle.scss]
    mainfont: Atkinson Hyperlegible
    toc: true
    linkcolor: "#0f7662"

editor: visual

execute:
  freeze: auto
