project:
  type: website
  output-dir: _site
  preview:
    port: 4200

  render:
    - "*.qmd"
    - "*.md"
    - "*.ipynb"
    - "*.Rmd"
    - "!CONTRIBUTING.md"
    - "!render_scripts/data/README-gh-pages.md"
    - "!webinars/dummy-webinar-page.qmd"

  post-render:
    - render_scripts/copy_gh_pages_readme.ts
    - render_scripts/github_link_insertion.ts

format:
  html:
    theme:
      light: [flatly, css/lightstyle.scss]
      dark: [darkly, css/darkstyle.scss]
    mainfont: Atkinson Hyperlegible
    css: css/styles.css
    toc: true

editor: visual

execute:
  freeze: auto

website:
  title: "JEDI Outreach Group"
  description: "The Justice, Equity, Diversity, and Inclusion (JEDI) Outreach Group, a community of statisticians and data scientists, is committed to communication, programming, and professional development to advance and support a society that values all people."
  favicon: "images/jedi-favicon-32px.ico"
  site-url: "https://datascijedi.org"
  repo-url: "https://github.com/datascijedi/website/"

  open-graph: true
  twitter-card:
    card-style: summary
    site: "@datascijedi"
    description: "The Justice, Equity, Diversity, and Inclusion (JEDI) Outreach Group, a community of statisticians and data scientists, is committed to communication, programming, and professional development to advance and support a society that values all people."
    image: "images/jedi-logo-square.png"

  page-navigation: true

  navbar:
    logo: images/jedi-logo-square.png
    logo-alt: "JEDI logo"
    align: center

    left:
      - text: "#JEDIatJSM"
        file: jedi-at-jsm.qmd
      - text: "About"
        file: about.qmd
      - text: "Activities"
        file: activities.qmd
      - jedi-corner.qmd
      - resources.qmd
      - text: "Get Involved"
        file: get-involved.qmd

    right:
      - icon: twitter
        href: https://twitter.com/datascijedi
        aria-label: Twitter
      - icon: linkedin
        href: https://www.linkedin.com/showcase/justice-equity-diversity-and-inclusion-organizing-group
        aria-label: LinkedIn
      - icon: instagram
        href: https://www.instagram.com/datascijedi/
        aria-label: Instagram
      - icon: facebook
        href: https://www.facebook.com/DataSciJEDI/
        aria-label: Facebook
      - icon: github
        href: https://github.com/datascijedi/website
        aria-label: GitHub

  sidebar:
    - title: "Activities"
      style: "floating"
      collapse-level: 2
      align: left
      border: true
      contents:
        - text: "Committees"
          file: activities.qmd
        - text: "Webinars"
          file: webinars.qmd
        - text: "Newsletter"
          file: weekly-newsletter.qmd
    - title: "Get Involved"
      style: "floating"
      collapse-level: 2
      align: left
      border: true
      contents:
        - text: "Get Involved"
          file: get-involved.qmd
        - text: "Spread the Word"
          file: spread-the-word.qmd
        - text: "Share Announcements"
          file: share-announcements.qmd

  page-footer:
    border: true
    left: "Copyright 2023 © JEDI"
    center: "GH-6c622c2fa6a54817" # placeholder text, replaced in post-render script
    right:
    - text: "License"
      href: LICENSE.md
    - text: "Code of Conduct"
      href: CODE_OF_CONDUCT.md
