name: Deploy Preview
on:
  workflow_dispatch:
  pull_request:
    branches: 
      - main
    type:
      - opened
      - synchronize
jobs:
  netlify-deploy-preview:
    name: Netlify Deploy Preview
    if: github.event_name == 'pull_request' && github.base_ref == 'main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: Render Quarto project
        uses: quarto-dev/quarto-actions/render@v2
      - name: Deploy to Netlify
        id: netlify-deploy-step
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: '_site'
          production-deploy: false
          deploy-message: "Deploy Preview from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: false
          overwrites-pull-request-comment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN_PROD }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_PROD }}
        timeout-minutes: 1
      - name: Add deploy preview link to PR comments
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Deploy preview: ${{ steps.netlify-deploy-step.outputs.deploy-url }}
