name: New Website Deploy Test
on:
  workflow_dispatch:
  push:
    branches: 
      - main
      - netlify-deploy-prep
  pull_request:
    branches: 
      - main
    type:
      - opened
      - synchronize
jobs:
  gh-pages-deploy:
    name: GitHub Pages Deploy
    if: |
      ${{ github.event_name == 'push' && github.ref_name == 'main' 
       || github.event_name == 'workflow_dispatch' && github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          folder: .        # The folder the action should deploy.
          branch: gh-pages # The branch the action should deploy to.
        timeout-minutes: 1
  netlify-deploy:
    if: ${{ github.event_name == 'push' && github.ref_name == 'netlify-deploy-prep' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: netlify
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN_TEST_RM }}
